spring.application.name=CloudVendorApplication
#Datasouce use to connect to DB
spring.datasource.url=jdbc:mysql://localhost:3306/cloud_vendor
spring.datasource.username=root
spring.datasource.password=Anubhab@2004
# same use for hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
